name: 'Promote Docker Images'
description: 'Adds the ability to re-tag and promote docker images'
author: 'Swimlane'
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  src:
    required: true
    description: 'The source image {registry}/{image}:{tag}'
  destinations:
    required: true
    description: 'List of all the destinations images {registry}/{image}:{tag}'
runs:
  using: node20
  main: dist/index.js
