name: 'build-test-ci'
on: # rebuild any PRs and main branch changes
  push:
      branches-ignore:
        - "release-please-**"
        - "main"

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          yarn
      - run: |
          yarn all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: ./
        with:
          src: docker.io/node:20
          destinations: |
            docker.io/u4ic/test-node:node-20
            docker.io/u4ic/test-node:latest
            docker.io/u4ic/test-node2:latest
